// Code generated by protoc-gen-go. DO NOT EDIT.
// source: balance_history_entry.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BalanceHistoryEntry struct {
	Transfer             *Transfer `protobuf:"bytes,1,opt,name=transfer,proto3" json:"transfer,omitempty"`
	Balance              uint64    `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *BalanceHistoryEntry) Reset()         { *m = BalanceHistoryEntry{} }
func (m *BalanceHistoryEntry) String() string { return proto.CompactTextString(m) }
func (*BalanceHistoryEntry) ProtoMessage()    {}
func (*BalanceHistoryEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6eff69733d21190, []int{0}
}

func (m *BalanceHistoryEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BalanceHistoryEntry.Unmarshal(m, b)
}
func (m *BalanceHistoryEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BalanceHistoryEntry.Marshal(b, m, deterministic)
}
func (m *BalanceHistoryEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalanceHistoryEntry.Merge(m, src)
}
func (m *BalanceHistoryEntry) XXX_Size() int {
	return xxx_messageInfo_BalanceHistoryEntry.Size(m)
}
func (m *BalanceHistoryEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_BalanceHistoryEntry.DiscardUnknown(m)
}

var xxx_messageInfo_BalanceHistoryEntry proto.InternalMessageInfo

func (m *BalanceHistoryEntry) GetTransfer() *Transfer {
	if m != nil {
		return m.Transfer
	}
	return nil
}

func (m *BalanceHistoryEntry) GetBalance() uint64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func init() {
	proto.RegisterType((*BalanceHistoryEntry)(nil), "proto.BalanceHistoryEntry")
}

func init() { proto.RegisterFile("balance_history_entry.proto", fileDescriptor_e6eff69733d21190) }

var fileDescriptor_e6eff69733d21190 = []byte{
	// 124 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4e, 0x4a, 0xcc, 0x49,
	0xcc, 0x4b, 0x4e, 0x8d, 0xcf, 0xc8, 0x2c, 0x2e, 0xc9, 0x2f, 0xaa, 0x8c, 0x4f, 0xcd, 0x2b, 0x29,
	0xaa, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x52, 0x7c, 0x25, 0x45, 0x89,
	0x79, 0xc5, 0x69, 0xa9, 0x45, 0x10, 0x61, 0xa5, 0x18, 0x2e, 0x61, 0x27, 0x88, 0x2e, 0x0f, 0x88,
	0x26, 0x57, 0x90, 0x1e, 0x21, 0x6d, 0x2e, 0x0e, 0x98, 0x42, 0x09, 0x46, 0x05, 0x46, 0x0d, 0x6e,
	0x23, 0x7e, 0x88, 0x06, 0xbd, 0x10, 0xa8, 0x70, 0x10, 0x5c, 0x81, 0x90, 0x04, 0x17, 0x3b, 0xd4,
	0x66, 0x09, 0x26, 0x05, 0x46, 0x0d, 0x96, 0x20, 0x18, 0x37, 0x89, 0x0d, 0xac, 0xc7, 0x18, 0x10,
	0x00, 0x00, 0xff, 0xff, 0xb7, 0x13, 0xaf, 0x10, 0x9a, 0x00, 0x00, 0x00,
}
