// Code generated by protoc-gen-go. DO NOT EDIT.
// source: input.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Input struct {
	CoinAmount           uint64   `protobuf:"varint,1,opt,name=coinAmount,proto3" json:"coinAmount,omitempty"`
	ReceivedTime         uint64   `protobuf:"varint,2,opt,name=receivedTime,proto3" json:"receivedTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Input) Reset()         { *m = Input{} }
func (m *Input) String() string { return proto.CompactTextString(m) }
func (*Input) ProtoMessage()    {}
func (*Input) Descriptor() ([]byte, []int) {
	return fileDescriptor_db6f7669dced820e, []int{0}
}

func (m *Input) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Input.Unmarshal(m, b)
}
func (m *Input) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Input.Marshal(b, m, deterministic)
}
func (m *Input) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Input.Merge(m, src)
}
func (m *Input) XXX_Size() int {
	return xxx_messageInfo_Input.Size(m)
}
func (m *Input) XXX_DiscardUnknown() {
	xxx_messageInfo_Input.DiscardUnknown(m)
}

var xxx_messageInfo_Input proto.InternalMessageInfo

func (m *Input) GetCoinAmount() uint64 {
	if m != nil {
		return m.CoinAmount
	}
	return 0
}

func (m *Input) GetReceivedTime() uint64 {
	if m != nil {
		return m.ReceivedTime
	}
	return 0
}

func init() {
	proto.RegisterType((*Input)(nil), "proto.Input")
}

func init() { proto.RegisterFile("input.proto", fileDescriptor_db6f7669dced820e) }

var fileDescriptor_db6f7669dced820e = []byte{
	// 98 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0xcc, 0x2b, 0x28,
	0x2d, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0xde, 0x5c, 0xac, 0x9e,
	0x20, 0x51, 0x21, 0x39, 0x2e, 0xae, 0xe4, 0xfc, 0xcc, 0x3c, 0xc7, 0xdc, 0xfc, 0xd2, 0xbc, 0x12,
	0x09, 0x46, 0x05, 0x46, 0x0d, 0x96, 0x20, 0x24, 0x11, 0x21, 0x25, 0x2e, 0x9e, 0xa2, 0xd4, 0xe4,
	0xd4, 0xcc, 0xb2, 0xd4, 0x94, 0x90, 0xcc, 0xdc, 0x54, 0x09, 0x26, 0xb0, 0x0a, 0x14, 0xb1, 0x24,
	0x36, 0xb0, 0x99, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf7, 0x69, 0x89, 0xbd, 0x69, 0x00,
	0x00, 0x00,
}
