// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transfer.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Transfer struct {
	Inputs               []*Input `protobuf:"bytes,1,rep,name=inputs,proto3" json:"inputs,omitempty"`
	SpentTime            uint64   `protobuf:"varint,2,opt,name=spentTime,proto3" json:"spentTime,omitempty"`
	BurnedMana           uint64   `protobuf:"varint,3,opt,name=burnedMana,proto3" json:"burnedMana,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transfer) Reset()         { *m = Transfer{} }
func (m *Transfer) String() string { return proto.CompactTextString(m) }
func (*Transfer) ProtoMessage()    {}
func (*Transfer) Descriptor() ([]byte, []int) {
	return fileDescriptor_96c3e6bcafb460d3, []int{0}
}

func (m *Transfer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transfer.Unmarshal(m, b)
}
func (m *Transfer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transfer.Marshal(b, m, deterministic)
}
func (m *Transfer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transfer.Merge(m, src)
}
func (m *Transfer) XXX_Size() int {
	return xxx_messageInfo_Transfer.Size(m)
}
func (m *Transfer) XXX_DiscardUnknown() {
	xxx_messageInfo_Transfer.DiscardUnknown(m)
}

var xxx_messageInfo_Transfer proto.InternalMessageInfo

func (m *Transfer) GetInputs() []*Input {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *Transfer) GetSpentTime() uint64 {
	if m != nil {
		return m.SpentTime
	}
	return 0
}

func (m *Transfer) GetBurnedMana() uint64 {
	if m != nil {
		return m.BurnedMana
	}
	return 0
}

func init() {
	proto.RegisterType((*Transfer)(nil), "proto.Transfer")
}

func init() { proto.RegisterFile("transfer.proto", fileDescriptor_96c3e6bcafb460d3) }

var fileDescriptor_96c3e6bcafb460d3 = []byte{
	// 130 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x29, 0x4a, 0xcc,
	0x2b, 0x4e, 0x4b, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x52, 0xdc,
	0x99, 0x79, 0x05, 0xa5, 0x25, 0x10, 0x31, 0xa5, 0x3c, 0x2e, 0x8e, 0x10, 0xa8, 0x2a, 0x21, 0x15,
	0x2e, 0x36, 0xb0, 0x54, 0xb1, 0x04, 0xa3, 0x02, 0xb3, 0x06, 0xb7, 0x11, 0x0f, 0x44, 0x8d, 0x9e,
	0x27, 0x48, 0x30, 0x08, 0x2a, 0x27, 0x24, 0xc3, 0xc5, 0x59, 0x5c, 0x90, 0x9a, 0x57, 0x12, 0x92,
	0x99, 0x9b, 0x2a, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x12, 0x84, 0x10, 0x10, 0x92, 0xe3, 0xe2, 0x4a,
	0x2a, 0x2d, 0xca, 0x4b, 0x4d, 0xf1, 0x4d, 0xcc, 0x4b, 0x94, 0x60, 0x06, 0x4b, 0x23, 0x89, 0x24,
	0xb1, 0x81, 0x8d, 0x34, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x61, 0xd4, 0xdc, 0x02, 0x9c, 0x00,
	0x00, 0x00,
}
