package shutdown

const (
	ShutdownPriorityDatabase = iota
	ShutdownPriorityTangle
	ShutdownPriorityFPC
	ShutdownPriorityRemoteLog
	ShutdownPriorityAnalysis
	ShutdownPriorityMetrics
	ShutdownPriorityAutopeering
	ShutdownPriorityGossip
	ShutdownPriorityWebAPI
	ShutdownPrioritySPA
	ShutdownPriorityGraph
	ShutdownPrioritySpammer
	ShutdownPriorityBadgerGarbageCollection
)
