// Code generated by protoc-gen-go. DO NOT EDIT.
// source: opinion_statement.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OpinionStatement struct {
	NodeId               []byte                `protobuf:"bytes,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Time                 uint64                `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	ToggledTransactions  []*ToggledTransaction `protobuf:"bytes,3,rep,name=toggledTransactions,proto3" json:"toggledTransactions,omitempty"`
	Signature            []byte                `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *OpinionStatement) Reset()         { *m = OpinionStatement{} }
func (m *OpinionStatement) String() string { return proto.CompactTextString(m) }
func (*OpinionStatement) ProtoMessage()    {}
func (*OpinionStatement) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5a0e519e658baf5, []int{0}
}

func (m *OpinionStatement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpinionStatement.Unmarshal(m, b)
}
func (m *OpinionStatement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpinionStatement.Marshal(b, m, deterministic)
}
func (m *OpinionStatement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpinionStatement.Merge(m, src)
}
func (m *OpinionStatement) XXX_Size() int {
	return xxx_messageInfo_OpinionStatement.Size(m)
}
func (m *OpinionStatement) XXX_DiscardUnknown() {
	xxx_messageInfo_OpinionStatement.DiscardUnknown(m)
}

var xxx_messageInfo_OpinionStatement proto.InternalMessageInfo

func (m *OpinionStatement) GetNodeId() []byte {
	if m != nil {
		return m.NodeId
	}
	return nil
}

func (m *OpinionStatement) GetTime() uint64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *OpinionStatement) GetToggledTransactions() []*ToggledTransaction {
	if m != nil {
		return m.ToggledTransactions
	}
	return nil
}

func (m *OpinionStatement) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func init() {
	proto.RegisterType((*OpinionStatement)(nil), "proto.OpinionStatement")
}

func init() { proto.RegisterFile("opinion_statement.proto", fileDescriptor_a5a0e519e658baf5) }

var fileDescriptor_a5a0e519e658baf5 = []byte{
	// 174 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcf, 0x2f, 0xc8, 0xcc,
	0xcb, 0xcc, 0xcf, 0x8b, 0x2f, 0x2e, 0x49, 0x2c, 0x49, 0xcd, 0x4d, 0xcd, 0x2b, 0xd1, 0x2b, 0x28,
	0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x52, 0x92, 0x25, 0xf9, 0xe9, 0xe9, 0x39, 0xa9, 0x29,
	0xf1, 0x25, 0x45, 0x89, 0x79, 0xc5, 0x89, 0xc9, 0x25, 0x99, 0xf9, 0x79, 0x10, 0x15, 0x4a, 0x2b,
	0x19, 0xb9, 0x04, 0xfc, 0x21, 0xba, 0x83, 0x61, 0x9a, 0x85, 0xc4, 0xb8, 0xd8, 0xf2, 0xf2, 0x53,
	0x52, 0x3d, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x78, 0x82, 0xa0, 0x3c, 0x21, 0x21, 0x2e, 0x96,
	0x92, 0xcc, 0xdc, 0x54, 0x09, 0x26, 0x05, 0x46, 0x0d, 0x96, 0x20, 0x30, 0x5b, 0xc8, 0x9b, 0x4b,
	0x18, 0x6a, 0x7a, 0x08, 0xc2, 0xf0, 0x62, 0x09, 0x66, 0x05, 0x66, 0x0d, 0x6e, 0x23, 0x49, 0x88,
	0x2d, 0x7a, 0x21, 0x18, 0x2a, 0x82, 0xb0, 0xe9, 0x12, 0x92, 0xe1, 0xe2, 0x2c, 0xce, 0x4c, 0xcf,
	0x4b, 0x2c, 0x29, 0x2d, 0x4a, 0x95, 0x60, 0x01, 0xdb, 0x8d, 0x10, 0x48, 0x62, 0x03, 0x1b, 0x66,
	0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x22, 0xe9, 0x1c, 0x03, 0xef, 0x00, 0x00, 0x00,
}
