// Code generated by protoc-gen-go. DO NOT EDIT.
// source: toggle_type.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ToggleType int32

const (
	ToggleType_Like    ToggleType = 0
	ToggleType_Dislike ToggleType = 1
)

var ToggleType_name = map[int32]string{
	0: "Like",
	1: "Dislike",
}

var ToggleType_value = map[string]int32{
	"Like":    0,
	"Dislike": 1,
}

func (x ToggleType) String() string {
	return proto.EnumName(ToggleType_name, int32(x))
}

func (ToggleType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f8d4c81885a98bf0, []int{0}
}

func init() {
	proto.RegisterEnum("proto.ToggleType", ToggleType_name, ToggleType_value)
}

func init() { proto.RegisterFile("toggle_type.proto", fileDescriptor_f8d4c81885a98bf0) }

var fileDescriptor_f8d4c81885a98bf0 = []byte{
	// 83 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0xc9, 0x4f, 0x4f,
	0xcf, 0x49, 0x8d, 0x2f, 0xa9, 0x2c, 0x48, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05,
	0x53, 0x5a, 0xca, 0x5c, 0x5c, 0x21, 0x60, 0xb9, 0x90, 0xca, 0x82, 0x54, 0x21, 0x0e, 0x2e, 0x16,
	0x9f, 0xcc, 0xec, 0x54, 0x01, 0x06, 0x21, 0x6e, 0x2e, 0x76, 0x97, 0xcc, 0xe2, 0x1c, 0x10, 0x87,
	0x31, 0x89, 0x0d, 0xac, 0xd6, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xad, 0x5e, 0x8a, 0xc7, 0x47,
	0x00, 0x00, 0x00,
}
